# Generated by Django 5.2.3 on 2025-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
